#!/bin/bash

# Setup TrueNAS and Nextcloud mounts
#
# /media/truenas/
# /media/nextcloud/


sudo mkdir -p /media/nextcloud
sudo mkdir -p /media/truenas

sudo chown simon:simon /media/nextcloud
sudo chown simon:simon /media/truenas

# check if .smbcredentials already exists
if [ -f /home/simon/.smbcredentials ]; then
    echo ".smbcredentials already exists, skipping."
else
    # TrueNAS login
    echo "TrueNAS username: "
    read truenas_username
    echo "TrueNAS password: "
    read -s truenas_password

    touch /home/simon/.smbcredentials
    echo "username=$truenas_username" >> /home/simon/.smbcredentials
    echo "password=$truenas_password" >> /home/simon/.smbcredentials
    sudo chmod 600 /home/simon/.smbcredentials
    sudo chown simon:simon /home/simon/.smbcredentials
fi

# check if the mount is already in fstab
if grep -q "//truenas.alle-schindlers.de/Daten" /etc/fstab; then
    echo "TrueNAS mount already exists in /etc/fstab, skipping."
else
    echo "Adding TrueNAS mount to /etc/fstab."
    sudo echo "//truenas.alle-schindlers.de/Daten /media/truenas cifs credentials=/home/simon/.smbcredentials,uid=simon,gid=simon,auto,rw 0 0" >> /etc/fstab
fi


if ! findmnt -rn --target /media/truenas &>/dev/null; then
    echo "Mounting /media/truenas..."
    sudo mount /media/truenas
else
    echo "/media/turnase is already mounted — skipping"
fi

if ! pacman -Qi nextcloud-client &>/dev/null; then
    sudo pacman -S --needed --noconfirm your-package-name

    echo "Login to Nextcloud in your browser."
    nextcloud

    # Wait for user to finish logging in
    echo "Press enter when you have logged in to Nextcloud."
    read

else
    echo "nextcloud-client was already installed — skipping setup"
fi



