return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	lazy = false,
}

-- 	dependencies = {
-- 		"nvim-treesitter/nvim-treesitter-textobjects",
-- 	},
--
-- 	config = function()
-- 		---@diagnostic disable-next-line: missing-fields
-- 		require("nvim-treesitter.config").setup({
-- 			ensure_installed = {
-- 				"bash",
-- 				"c",
-- 				"cpp",
-- 				"dockerfile",
-- 				"fish",
-- 				"gitignore",
-- 				"json",
-- 				"html",
-- 				"lua",
-- 				"markdown",
-- 				"vim",
-- 				"vimdoc",
-- 				"rust",
-- 				"toml",
-- 				"python",
-- 				"typescript",
-- 				"json",
-- 				"yaml",
-- 			},
-- 			auto_install = true,
-- 			highlight = {
-- 				enable = true,
-- 				additional_vim_regex_highlighting = { "markdown" },
-- 			},
-- 			indent = { enable = true },
-- 			textobjects = {
-- 				select = {
-- 					enable = true,
-- 					lookahead = true,
-- 					keymaps = {
-- 						["aa"] = "@parameter.outer",
-- 						["ia"] = "@parameter.inner",
-- 						["af"] = "@function.outer",
-- 						["if"] = "@function.inner",
-- 						["ac"] = "@class.outer",
-- 						["ic"] = "@class.inner",
-- 					},
-- 				},
-- 				swap = {
-- 					enable = true,
-- 					swap_next = {
-- 						["<leader>a"] = "@parameter.inner",
-- 					},
-- 					swap_previous = {
-- 						["<leader>A"] = "@parameter.inner",
-- 					},
-- 				},
-- 			},
-- 		})
-- 	end,
-- }
